# Generated by Django 5.1.3 on 2024-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_salon_services', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=2, upload_to='news_images/'),
            preserve_default=False,
        ),
    ]
