# Generated by Django 5.1.3 on 2024-12-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_salon_services', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], max_length=100),
        ),
    ]
